name: rsd
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==1.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.19.0
      - akro==0.0.8
      - ale-py==0.11.2
      - anyio==3.7.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-lru==2.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - better-exceptions==0.3.3
      - bleach==6.0.0
      - box2d-py==2.3.8
      - cachetools==5.3.1
      - certifi==2023.5.7
      - cffi==1.15.1
      - chardet==5.2.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==1.3.0
      - cma==2.7.0
      - cmake==4.1.2
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.35
      - d4rl==1.1
      - debugpy==1.6.7
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dm-control==1.0.5
      - dm-env==1.5
      - dm-tree==0.1.7
      - docker-pycreds==0.4.0
      - dowel==0.0.4
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fasteners==0.18
      - fastjsonschema==2.17.1
      - filelock==3.12.0
      - flatbuffers==25.9.23
      - fonttools==4.39.4
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - future==0.18.3
      - garage==2020.6.0
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.9
      - google-auth==2.19.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - gym==0.17.2
      - gym-notices==0.0.8
      - h5py==3.15.1
      - idna==3.4
      - imageio==2.31.0
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - iod==0.0.0
      - ipykernel==6.23.1
      - ipython==8.12.2
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.5.2
      - json5==0.9.14
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-lsp==2.2.0
      - jupyter-server==2.6.0
      - jupyter-server-fileid==0.9.0
      - jupyter-server-terminals==0.4.4
      - jupyter-server-ydoc==0.6.1
      - jupyter-ydoc==0.2.4
      - jupyterlab==3.6.1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.22.1
      - jupyterlab-vim==0.16.0
      - keras==2.15.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - lazy-loader==0.2
      - libclang==16.0.0
      - lit==18.1.8
      - lxml==4.9.2
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - ml-dtypes==0.2.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mujoco==2.2.1
      - mujoco-py==2.1.2.14
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.9.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.3
      - numpy-quaternion==2022.4.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.2.2
      - opencv-python==4.7.0.72
      - opt-einsum==3.3.0
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.5.1
      - proglog==0.1.10
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybullet==3.2.7
      - pycparser==2.21
      - pyglet==1.5.0
      - pygments==2.15.1
      - pyopengl==3.1.7
      - pyparsing==2.4.7
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.1.0
      - ray==2.51.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.25.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - triton==3.5.1
      - typing-extensions==4.15.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - urllib3==1.26.16
      - wandb==0.15.4
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - werkzeug==2.3.4
      - wrapt==1.14.2
      - y-py==0.5.9
      - ypy-websocket==0.8.2
      - zipp==3.15.0
prefix: /home/juhasz/miniforge3/envs/rsd
